export ZSH="$HOME/.oh-my-zsh"

HYPHEN_INSENSITIVE="true"

plugins=(
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# sources
source /etc/profile.d/vte.sh

# exports
export EDITOR=/bin/nvim

export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# aliases
alias r="ranger -r ~/dotfiles/firstlove/ranger"
alias htop="htop --tree"
alias mounts="mount | grep -E '(/dev/sd|@|ifuse)'"
alias tig="tig --all"
alias tl="trash-list"

# pacman aliases
alias pacc="pacman -Q | wc -l"
alias pacl="pacman -Q | fzf"
alias paci="sudo pacman -S"
alias pacr="sudo pacman -R"
alias pacu="sudo pacman -Syu"
alias pacac="bat /var/log/pacman.log | fzf --reverse --tac --no-sort"
alias pacclean="sudo pacman -Rns $(pacman -Qtdq)"
alias paccachedrop="sudo pacman -Scc"

# config files
alias cfmutt="${EDITOR} ~/.neomutt/neomuttrc"
alias cfmbsync="${EDITOR} ~/.mbsyncrc"
alias cfmsmpt="${EDITOR} ~/.msmtprc"

# git aliases
alias gits="git status"
alias gitl="git log"
alias gita="git add"
alias gitc="git commit"
alias gitp="git push"
alias gitd="git diff"
alias gitb="git branch"

# mount aliases
alias mountwinc="sudo mount /dev/sda4 $HOME/mounts/winc"
alias umountwinc="sudo umount $HOME/mounts/winc"
alias mounthyperdrive="sudo mount /dev/sda5 $HOME/mounts/hyperdrive"
alias umounthyperdrive="sudo umount $HOME/mounts/hyperdrive"
alias mountubuntu="sudo mount /dev/sda7 $HOME/mounts/ubuntu"
alias umountubuntu="sudo umount $HOME/mounts/ubuntu"

eval "$(starship init zsh)"
