config.set('fonts.default_size', '12pt')
config.set('spellcheck.languages', ['en-US'])
config.set('colors.completion.even.bg', '#000000')
config.set('colors.completion.odd.bg', '#111111')
config.set('colors.completion.item.selected.bg', '#ffffff')
config.set('colors.completion.even.bg', '#000000')
config.set('colors.tabs.even.bg', '#000000')
config.set('colors.tabs.odd.bg', '#000000')
config.set('colors.tabs.selected.even.bg', '#999999')
config.set('colors.tabs.selected.odd.bg', '#999999')
config.set('colors.tabs.selected.even.fg', '#000000')
config.set('colors.tabs.selected.odd.fg', '#000000')
config.set('tabs.padding', {"bottom": 3, "left": 5, "right": 5, "top": 3})
config.set('tabs.indicator.padding', {"bottom": 0, "left": 0, "right": 4, "top": 0})

config.bind('<ctrl-tab>', 'tab-next')
config.bind('<ctrl-shift-tab>', 'tab-prev')
config.bind('<ctrl-r>', 'config-source')
config.bind('<ctrl-h>', 'history')
config.bind('<alt-left>', 'back')
config.bind('<alt-right>', 'forward')
config.bind('q', 'tab-close')
config.bind('d', 'record-macro')
