config.set('fonts.default_size', '12pt')
config.set('spellcheck.languages', ['en-US'])
config.set('colors.completion.even.bg', '#000000')
config.set('colors.completion.odd.bg', '#111111')
config.set('colors.completion.item.selected.bg', '#ffffff')
config.set('colors.completion.even.bg', '#000000')
config.set('colors.tabs.even.bg', '#000000')
config.set('colors.tabs.odd.bg', '#000000')
config.set('colors.tabs.selected.even.bg', '#999999')
config.set('colors.tabs.selected.odd.bg', '#999999')
config.set('colors.tabs.selected.even.fg', '#000000')
config.set('colors.tabs.selected.odd.fg', '#000000')
config.set('tabs.padding', {"bottom": 7, "left": 2, "right": 0, "top": 7})
config.set('tabs.indicator.padding', {"bottom": 0, "left": 0, "right": 4, "top": 0})
config.set('downloads.location.directory', '~/')
config.set('downloads.location.suggestion', 'both')
config.set('downloads.position', 'bottom')
config.set('downloads.position', 'bottom')
config.set('input.insert_mode.auto_load', False)
config.set('tabs.last_close', 'close')
config.set('url.searchengines', {"DEFAULT": "https://www.google.com/search?q={}"})

config.unbind('<ctrl-v>', mode='normal')
config.unbind('u', mode='normal')
config.unbind('q', mode='normal')
config.unbind('<ctrl-Q>', mode='normal')
config.unbind('<ctrl-W>', mode='normal')

config.bind('<ctrl-tab>', 'tab-next')
config.bind('<ctrl-shift-tab>', 'tab-prev')
config.bind('<ctrl-r>', 'config-source')
config.bind('<ctrl-h>', 'history')
config.bind('<ctrl-shift-left>', 'tab-move -')
config.bind('<ctrl-shift-right>', 'tab-move +')
config.bind('<alt-left>', 'back')
config.bind('<alt-right>', 'forward')
config.bind('d', 'record-macro')
config.bind('qq', 'tab-close')

config.bind('gy', 'open https://www.youtube.com')
config.bind('gc', 'open https://canvas.umn.edu')
config.bind('gc', 'open https://canvas.umn.edu')

config.unbind('gm', mode='normal')
config.bind('gm1', 'open https://mail.google.com/mail/u/0/#inbox')
config.bind('gm2', 'open https://mail.google.com/mail/u/1/#inbox')
config.bind('gm3', 'open https://mail.google.com/mail/u/2/#inbox')
config.bind('gm4', 'open https://mail.google.com/mail/u/3/#inbox')
