format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$cmake\
$golang\
$java\
$julia\
$kotlin\
$nodejs\
$php\
$python\
$rust\
$conda\
$memory_usage\
$aws\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

add_newline = false

[line_break]
disabled = true

[[battery.display]]
threshold = 50
style = "bold red"
