#!/bin/bash

NUM_FILES=$(ls /sys/class/bluetooth | wc -w)
if [ ${NUM_FILES} -eq 1 ];
then
  echo "Disconnected"
else
  INFO=$(bluetoothctl info)
  if [ $? -eq 0 ]; then
    NAME=$(bluetoothctl info | grep Name | awk '{ for (i = 2; i <= NF; i++) s = s $i " "; print s }')
    echo ${NAME}
  else
    echo "Error"
  fi
fi

