#!/bin/bash

ACTUAL_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
MAX_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)

PERCENTAGE_BRIGHTNESS=$(echo "scale=2;${ACTUAL_BRIGHTNESS}/${MAX_BRIGHTNESS}*100" | bc -l | xargs printf "%.0f%%\n")

echo $PERCENTAGE_BRIGHTNESS
