#! /bin/bash

# Uses mbsync to sync mailboxes and check for new mails
# mbsync configuration (imap settings, password, mailboxes etc...) for all accounts is assumed to be complete

ACCOUNTS=( "yash.3997@gmail.com" "yspatkuri@gmail.com" "patku001@umn.edu" )
NEW_MAIL_TOTAL=0

for ACCOUNT in "${ACCOUNTS[@]}"
do
  NEW_MAIL_COUNT=$(mbsync ${ACCOUNT} > /dev/null && ls ~/.mail/${ACCOUNT}/inbox/new  | wc -l)
  if [ $NEW_MAIL_COUNT \> 0 ];
  then
    NEW_MAIL_TOTAL=$((NEW_MAIL_TOTAL+1))
    pgrep -x dunst >/dev/null && notify-send -u critical -a "📬 Mail" "${ACCOUNT}" "${NEW_MAIL_COUNT} new mail"
  fi;
done

echo "📬 ${NEW_MAIL_TOTAL}*"
