#!/bin/bash

CAPACITY=$(cat /sys/class/power_supply/BAT1/capacity) || exit
STATUS=$(cat /sys/class/power_supply/BAT1/status)

if [ "$CAPACITY" -ge 80 ]; then
  color="#00FF00"
elif [ "$CAPACITY" -ge 60 ]; then
  color="#FFFFFF"
elif [ "$CAPACITY" -ge 40 ]; then
  color="#FFF600"
elif [ "$CAPACITY" -ge 20 ]; then
  color="#FFAE00"
else
  color="#FF0000"
fi

[ "$STATUS" = "Charging" ] && color="#FFF"

echo $CAPACITY% $STATUS
