#! /bin/bash
xrandr --auto
xrdb ~/.Xresources
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo 80%
xrandr --output eDP1 --brightness 0.35
~/dotfiles/blackpanther/bg_changer > /dev/null &
echo
echo
pwd
echo
echo
xcompmgr &
exec i3 -c ~/dotfiles/blackpanther/i3/config
# exec dbus-launch leftwm
