#!/bin/bash

EMOJI=$(cat ~/.i3scripts/emojis.csv | dmenu -i -l 20 -fn FiraMono-12 -b -p 'Select an emoji' | awk -F "," '{print $1}' | tr -d '\n')

if [ "${EMOJI}" != "" ]; then
  xclip <(echo ${EMOJI}) -selection clipboard && pgrep dunst > /dev/null && notify-send "\"$(xclip -o -selection clipboard)\" is copied into clipboard"
fi
